name: VAE_MTECH
seed: 1234
track: &track True
model:
  class_name: CompressedUNET
  module_name: src.models.unet.compressed
  parameters:
    in_channels: 1
    out_channels: 1
    features: !!python/list [64, 128, 256, 512, 1024]

dataloader:
  class_name: CIFAR10Loader
  module_name: src.data.loaders.cifar10
  parameters:
    data_dir: ./data
    input_size: !!python/tuple [64, 64]
    batch_size: 32
    num_workers: 4

trainer:
  class_name: VAETrainer
  module_name: experiments.vae.trainer
  parameters:
    num_epochs: 5
    early_stopping_patience: 20
    lr_scheduler: plateau
    lr: 0.0001
    weight_decay: 0.00001
    track: *track
    loss:
      module_name: src.optimisation.losses
      class_name: VAELoss
      parameters:
        kld_weight: 0.0005

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
  parameters:
    metrics_type: classification