name: DefaultTask
seed: 1234
track: &track False
script_path: /home/jovyan/work
scaling_factor: &scaling_factor 2

model:
  class_name: DefaultCNN
  module_name: src.models.default
  parameters:

dataloader:
  class_name: DefaultDataloader
  module_name: src.data.loaders.default
  parameters:
    data_dir: ./data
    batch_size: 32
    num_workers: 4
    debug: False

trainer:
  class_name: DefaultTrainer
  module_name: tasks.default.trainer
  parameters:
    num_epochs: 10
    early_stopping_patience: 10
    lr_scheduler: plateau
    lr: 0.001
    weight_decay: 0.00001
    track: *track
    loss:
      class_name: CrossEntropyLoss
      module_name: torch.nn
      parameters:
    
    metrics:
      - accuracy:
        class_name: Accuracy
        module_name: torchmetrics
        parameters:
          task: multiclass
          num_classes: 10
      - auroc:
        class_name: AUROC
        module_name: torchmetrics
        parameters:
          task: multiclass
          num_classes: 10

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
