name: CIFAR10
seed: 1234
model:
  class_name: MNISTNet
  module_name: src.models.mnist
  parameters:
    in_channels: 3
    out_channels: 10

dataloader:
  class_name: CIFAR10Loader
  module_name: src.data.loaders.cifar10
  parameters:
    data_dir: ./data
    input_size: !!python/tuple [28, 28]
    batch_size: 8
    num_workers: 4

trainer:
  class_name: CIFAR10Trainer
  module_name: experiments.cifar10.trainer
  parameters:
    num_epochs: 5
    early_stopping_patience: 20
    lr_scheduler: plateau
    lr: 0.0001
    weight_decay: 0.00001
    loss:
      module_name: torch.nn
      class_name: CrossEntropyLoss
      parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
  parameters:
    metrics_type: classification